#!/usr/bin/zsh

# Set colors
autoload colors zsh/terminfo
if [[ "$terminfo[colors]" -ge 8 ]]; then
	colors
fi
for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
	eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
	eval PR_BOLD_$color='%{$fg[${(L)color}]%}'
	(( count = $count + 1 ))
done
PR_NO_COLOR="%{$terminfo[sgr0]%}"

# Prompt
#PS1="[$PR_BLUE%n$PR_GREEN@%m$PR_NO_COLOR:$PR_RED%2c$PR_NO_COLOR]$PR_WHITE%(!.#.$)$PR_NO_COLOR "
# Right Justified Prompt
# RPS1="$PR_BOLD_YELLOW(%D{%m-%d %H:%M})$PR_NO_COLOR"
source ~/.zsh_prompt

# ls colors
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
fi

### Aliases
alias randmac="head /dev/urandom | openssl md5 | sed 's/\(..\)/\1:/g' | cut -c1-17"
alias rm='mv --verbose -i --target-directory ~/.Trash/'
alias empty='/bin/rm -rvf ~/.Trash/* ; /bin/rm -rvf ~/.Trash/.*'
alias lltr='ll -tr'
alias lla='ls -lhA'
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'
alias mutt='TERM=xterm-256color mutt'
alias c='clear'
alias gl='git log --pretty=oneline'
alias gits='git status'
alias o='gvfs-open'
alias h='history'
alias du='du -hsc'
alias df='df -hTP'
alias g=gvim
alias v=vim

alias s1='ssh -X saguaro1.fulton.asu.edu'
alias 360slice='ssh -X adigiro@67.207.147.15'

### Variables
export EDITOR=vim
export PATH=/opt/e17/bin:$PATH
export PATH=$HOME/Preferences/bin:$PATH

export GDBASE_PREFIX=/home/adigiro/apps/gdbase
export PATH=$HOME/apps/gdbase/bin:$PATH

### MVAPICH
#export PATH=$HOME/apps/mvapich/bin:/home/adigiro/apps/valgrind-mvapich/bin:$PATH
#export LD_LIBRARY_PATH=$HOME/mvapich/lib:$LD_LIBRARY_PATH

### OPENMPI 1.2.6
#export PATH=$HOME/apps/openmpi126/bin:/home/adigiro/apps/valgrind-openmpi/bin:$PATH
#export LD_LIBRARY_PATH=$HOME/apps/openmpi126/lib/openmpi:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=$HOME/apps/openmpi126/lib:$LD_LIBRARY_PATH

# OPENMPI 1.3.3
export PATH=$HOME/apps/openmpi133/bin:$PATH
export LD_LIBRARY_PATH=$HOME/apps/openmpi133/lib/openmpi:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$HOME/apps/openmpi133/lib:$LD_LIBRARY_PATH

function authme {
    ssh $@ 'cat >>.ssh/authorized_keys' <~/.ssh/id_rsa.pub
}

#Emacs Mode
bindkey -e
#VI Mode
#bindkey -v

setopt MENUCOMPLETE

setopt INC_APPEND_HISTORY APPEND_HISTORY SHARE_HISTORY
setopt HIST_IGNORE_DUPS HIST_IGNORE_ALL_DUPS
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zhistory


##setopt NOHUP
##setopt NOTIFY
##setopt NO_FLOW_CONTROL
#setopt APPEND_HISTORY
## setopt AUTO_LIST		# these two should be turned off
## setopt AUTO_REMOVE_SLASH
## setopt AUTO_RESUME	# tries to resume command of same name
#unsetopt BG_NICE		# do NOT nice bg commands
#setopt CORRECT			# command CORRECTION
#setopt EXTENDED_HISTORY	# puts timestamps in the history
## setopt HASH_CMDS		# turns on hashing
#setopt ALL_EXPORT
#
## Set/unset shell options
#setopt   notify globdots correct pushdtohome cdablevars autolist
#setopt   correctall autocd recexact longlistjobs
#setopt   autoresume histignoredups pushdsilent 
#setopt   autopushd pushdminus extendedglob rcquotes mailwarning
#unsetopt bgnice autoparamslash
#
## Autoload zsh modules when they are referenced
#zmodload -a zsh/stat stat
#zmodload -a zsh/zpty zpty
#zmodload -a zsh/zprof zprof
#zmodload -ap zsh/mapfile mapfile
#
#HOSTNAME="`hostname`"
#PAGER='less'
#EDITOR='vim'


#unsetopt ALL_EXPORT
#autoload -U compinit
#compinit

bindkey "^?" backward-delete-char
bindkey '^[[1~' vi-beginning-of-line
bindkey '^[[4~' vi-end-of-line
#bindkey '^[[5~' up-line-or-history
#bindkey '^[[6~' down-line-or-history
bindkey "^r" history-incremental-search-backward
bindkey ' ' magic-space    # also do history expansion on space
bindkey '^I' complete-word # complete on tab, leave expansion to _expand

#autoload zkbd
#[[ -n ${key[Backspace]} ]] && bindkey "${key[Backspace]}" backward-delete-char
#[[ -n ${key[Insert]} ]] && bindkey "${key[Insert]}" overwrite-mode
#[[ -n ${key[Home]} ]] && bindkey "${key[Home]}" beginning-of-line
#[[ -n ${key[PageUp]} ]] && bindkey "${key[PageUp]}" up-line-or-history
#[[ -n ${key[Delete]} ]] && bindkey "${key[Delete]}" delete-char
#[[ -n ${key[End]} ]] && bindkey "${key[End]}" end-of-line
#[[ -n ${key[PageDown]} ]] && bindkey "${key[PageDown]}" down-line-or-history
#[[ -n ${key[Up]} ]] && bindkey "${key[Up]}" up-line-or-search
#[[ -n ${key[Left]} ]] && bindkey "${key[Left]}" backward-char
#[[ -n ${key[Down]} ]] && bindkey "${key[Down]}" down-line-or-search
#[[ -n ${key[Right]} ]] && bindkey "${key[Right]}" forward-char

zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path ~/.zsh/cache/$HOST

zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' menu select=1 _complete _ignored _approximate
zstyle -e ':completion:*:approximate:*' max-errors \
    'reply=( $(( ($#PREFIX+$#SUFFIX)/2 )) numeric )'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'

# Completion Styles
# list of completers to use
zstyle ':completion:*::::' completer _expand _complete _ignored _approximate
# allow one error for every three characters typed in approximate completer
zstyle -e ':completion:*:approximate:*' max-errors \
    'reply=( $(( ($#PREFIX+$#SUFFIX)/2 )) numeric )'
# insert all expansions for expand completer
zstyle ':completion:*:expand:*' tag-order all-expansions
# formatting and messages
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*:corrections' format '%B%d (errors: %e)%b'
zstyle ':completion:*' group-name ''

# match uppercase from lowercase
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
# offer indexes before parameters in subscripts
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters

# command for process lists, the local web server details and host completion
# on processes completion complete all user processes
# zstyle ':completion:*:processes' command 'ps -au$USER'


## add colors to processes for kill completion
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

#zstyle ':completion:*:processes' command 'ps ax -o pid,s,nice,stime,args | sed "/ps/d"'
zstyle ':completion:*:*:kill:*:processes' command 'ps --forest -A -o pid,user,cmd'
zstyle ':completion:*:processes-names' command 'ps axho command' 
#zstyle ':completion:*:urls' local 'www' '/var/www/htdocs' 'public_html'
#

#NEW completion:
# 1. All /etc/hosts hostnames are in autocomplete
# 2. If you have a comment in /etc/hosts like #%foobar.domain,
#    then foobar.domain will show up in autocomplete!
zstyle ':completion:*' hosts $(awk '/^[^#]/ {print $2 $3" "$4" "$5}' /etc/hosts | grep -v ip6- && grep "^#%" /etc/hosts | awk -F% '{print $2}') 
# Filename suffixes to ignore during completion (except after rm command)
zstyle ':completion:*:*:(^rm):*:*files' ignored-patterns '*?.o' '*?.c~' \
    '*?.old' '*?.pro'
# the same for old style completion
#fignore=(.o .c~ .old .pro)


# ignore completion functions (until the _ignored completer)
#zstyle ':completion:*:functions' ignored-patterns '_*'
#zstyle ':completion:*:*:*:users' ignored-patterns \
#        adm apache bin daemon games gdm halt ident junkbust lp mail mailnull \
#        named news nfsnobody nobody nscd ntp operator pcap postgres radvd \
#        rpc rpcuser rpm shutdown squid sshd sync uucp vcsa xfs avahi-autoipd\
#        avahi backup messagebus beagleindex debian-tor dhcp dnsmasq fetchmail\
#        firebird gnats haldaemon hplip irc klog list man cupsys postfix\
#        proxy syslog www-data mldonkey sys snort
#
## SSH Completion
#zstyle ':completion:*:scp:*' tag-order \
#   files users 'hosts:-host hosts:-domain:domain hosts:-ipaddr"IP\ Address *'
#zstyle ':completion:*:scp:*' group-order \
#   files all-files users hosts-domain hosts-host hosts-ipaddr
#zstyle ':completion:*:ssh:*' tag-order \
#   users 'hosts:-host hosts:-domain:domain hosts:-ipaddr"IP\ Address *'
#zstyle ':completion:*:ssh:*' group-order \
#   hosts-domain hosts-host users hosts-ipaddr
#zstyle '*' single-ignored show
