#!/bin/bash
wget "http://downloads.sourceforge.net/project/zsh/zsh/5.0.0/zsh-5.0.0.tar.bz2"

tar xvf zsh-5.0.0.tar.bz2
cd zsh-5.0.0

PREFIX=/sw/cave/zsh/5.0.0/centos5.8_gnu4.1.2
./configure \
 --prefix=$PREFIX \
 --enable-fndir=$PREFIX/zsh/functions \
 --enable-scriptdir=$PREFIX/zsh/scripts \
 --enable-site-fndir=$PREFIX/share/zsh/site-functions \
 --enable-site-scriptdir=$PREFIX/share/zsh/site-scripts \
 --enable-cap \
 --enable-maildir-support \
 --enable-multibyte \
 --enable-pcre \
 --enable-zsh-secure-free \
 --with-tcsetpgrp \
 --disable-etcdir

sed -i -e 's/link=dynamic/link=static/g' config.modules

make
rm -rf $PREFIX
make install

rm -rvf ~/.zcompdump

