#!/bin/bash
wget 'https://git-core.googlecode.com/files/git-1.8.1.tar.gz'
wget 'https://git-core.googlecode.com/files/git-manpages-1.8.1.tar.gz'

tar xvf git-1.8.1.tar.gz
cd git-1.8.1

./configure --prefix=/sw/cave/git/1.8.1/centos5.8_gnu4.1.2
make
make install

