#!/bin/bash
if [[ ! -e bash-4.2.tar.gz ]]; then
  wget 'http://ftpmirror.gnu.org/bash/bash-4.2.tar.gz'
fi
rm -rf bash-4.2
tar xvf bash-4.2.tar.gz
cd bash-4.2

./configure --prefix=$HOME/apps/bash-4.2
make
make install

