#!/bin/sh
PREFIX=/sw/cave/tmux/1.7/centos5.8_gnu4.1.2

export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig

wget 'https://github.com/downloads/libevent/libevent/libevent-2.0.21-stable.tar.gz'
tar xvf libevent-2.0.21-stable.tar.gz
cd libevent-2.0.21-stable
./configure --prefix=$PREFIX --enable-static
make
make install

cd ..

wget 'http://downloads.sourceforge.net/project/tmux/tmux/tmux-1.7/tmux-1.7.tar.gz'
tar xvf tmux-1.7.tar.gz
cd tmux-1.7
./configure --prefix=$PREFIX --enable-static
make
make install

