#!/bin/sh -x
killall dhcpcd
/sbin/ip link set wlan0 down
sleep 1
/sbin/ip link set wlan0 up
sleep 1
#ifconfig wlan0 up
/usr/sbin/wpa_supplicant -D wext -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf.anthony -B
#iwconfig wlan0 essid "ornl-visitor"
sleep 1
/sbin/dhcpcd wlan0
